#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_spout = env_modules.Clone()

env_spout.add_source_files(env.modules_sources, "*.cpp")

spout_binary_dir = "#thirdparty/spout-library/Binaries/x64/"
env.Append(LIBS=[File(spout_binary_dir + "SpoutLibrary.lib")])

env.CommandNoCache(
    "#bin/SpoutLibrary.dll",
    spout_binary_dir + "SpoutLibrary.dll",
    Copy("$TARGET", "$SOURCE"),
)
